---
# Additionnal page configuration

# Additionnal configurations are loaded using its file name, minus the extension, as an anchor (https://<mydashboad>#<config>). 
# `config.yml` is still used as a base configuration, and all values here will overwrite it, so you don't have to re-defined everything


subtitle: "小项目"

# This overwrites message config. Setting it to empty to remove message from this page and keep it only in the main one:
message: ~

# as we want to include a differente link here (so we can get back to home page), we need to replicate all links or they will be revome when overwriting the links field:
links:
  - name: "工具栏"
    icon: "fa fa-layer-group"
    url: "#Tool"
  - name: "小项目"
    icon: "fa fa-lightbulb"
    url: "#Project"
    # target: "_blank"
  - name: "兵器库"
    icon: "fas fa-skull"
    url: "#Arsenal" 

services:
  - name: "突发奇想"
    icon: "fas fa-grin-squint-tears"
    items:
      - name: "句子"
        logo: "assets/logos/setence.png"
        subtitle: "要变得优秀，堵住那些悠悠众口。"
        tag: "Virts"
        url: "https://sentence.virts.app"
        target: "_blank"
